on:
  push:
  schedule:
    - cron: "* * * * *"

name: Update a pinned gist with crypto price

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: "40b6a7b4e19c1526619df8f99fbd522a"
          PRODUCT_ID: "BTC-USD"
